In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

In [3]:
df = pd.DataFrame(data)

In [4]:
print('Data from before new column')
df.head()

Data from before new column

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [ ]:
address = ['NYC', 'NJ', '']

In [6]:
print('Before Column Add:')
df.head()

Before Column Add:

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [23]:
df['Total Score'] = df['score 1'] + df['score 2']

print('after Column add:')

KeyError: 'score 1'

In [5]:
df['Avg_Score'] = df['Total Score'] / 2
df(head)

KeyError: 'Total Score'

In [10]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]

In [12]:
df3 = pd.DataFrame(values, columns=['Name', 'Univ_Marks'])

df3.head()

     Name  Univ_Marks
0   Rohan         455
1  Elvish         250
2    John         495
3     Sai         400
4    Eric         350

In [13]:
df3['Percentage'] = (df3['Univ_Marks'] / 500) * 100

df3.head()

     Name  Univ_Marks  Percentage
0   Rohan         455        91.0
1  Elvish         250        50.0
2    John         495        99.0
3     Sai         400        80.0
4    Eric         350        70.0

### Using the .insert() method to add column

In [20]:
df3.insert(1, 'Age', [1000, 2000, 50, 60, 12, 13])

df3.head()

ValueError: cannot insert Age, already exists

In [17]:
df3.head()

     Name   Age  Univ_Marks  Percentage
0   Rohan  1000         455        91.0
1  Elvish  2000         250        50.0
2    John    50         495        99.0
3     Sai    60         400        80.0
4    Eric    12         350        70.0

In [18]:
df3 =df3.assign(location=['MiddleEarth', 'Forgotten Lands', 'NYC', 'NJ', 'CA', 'MA'])

df3.head()

     Name   Age  Univ_Marks  Percentage         location
0   Rohan  1000         455        91.0      MiddleEarth
1  Elvish  2000         250        50.0  Forgotten Lands
2    John    50         495        99.0              NYC
3     Sai    60         400        80.0               NJ
4    Eric    12         350        70.0               CA