In [40]:
import pandas as pd
import numpy as np

In [41]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]

In [42]:
df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'weight', 'Salary'])

In [43]:
df.head()

      Name   Age  weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [44]:
# provides summarization of missing values per column
df.isnull().sum()

Name      1
Age       3
weight    1
Salary    2
dtype: int64

# be weary of missing values if you have a small dataset, removing values can dramatically alter your analysis sir

# if missing data rows is  less than 5% then its ok to delete them

In [45]:
dropped_df = df.dropna()

print(dropped_df)

        Name   Age  weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [46]:
filled_df = df.fillna('NaN')

filled_df

        Name   Age weight     Salary
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0    NaN  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0        NaN
9        NaN  42.0   85.0        NaN
10     Jenny   NaN  100.0    25632.0
11      Kenn   NaN  110.0    25632.0
12       Aly   NaN   90.0    25582.0
13      John  41.0   85.0  1528000.0

In [47]:
filled_df.isnull().sum()

Name      0
Age       0
weight    0
Salary    0
dtype: int64

In [48]:
specific_cols =df[['weight', 'Age']].fillna('Pending')
specific_cols

     weight      Age
0      75.0     36.0
1      74.0     38.0
2      70.0     31.0
3      80.0     34.0
4     100.0     40.0
5   Pending     40.0
6      72.0     33.0
7      85.0     42.0
8      85.0     42.0
9      85.0     42.0
10    100.0  Pending
11    110.0  Pending
12     90.0  Pending
13     85.0     41.0

In [49]:
df2 = df.fillna(value={'Weight': 'Pending', 'Age': 'Unknown', 'Salary': '0.0', 'Name': 'Verification Pending'})

df2

                    Name      Age  weight     Salary
0                  James     36.0    75.0  5428000.0
1                Villers     38.0    74.0  3428000.0
2                  VKole     31.0    70.0  8428000.0
3                  Smith     34.0    80.0  4428000.0
4                  Gayle     40.0   100.0  4528000.0
5                   Adam     40.0     NaN  4528000.0
6                 Rooter     33.0    72.0  7028000.0
7               Peterson     42.0    85.0  2528000.0
8                  lynda     42.0    85.0        0.0
9   Verification Pending     42.0    85.0        0.0
10                 Jenny  Unknown   100.0    25632.0
11                  Kenn  Unknown   110.0    25632.0
12                   Aly  Unknown    90.0    25582.0
13                  John     41.0    85.0  1528000.0

In [50]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }

tech = pd.DataFrame(technologies)

In [51]:
tech.isnull().sum()

Courses     2
Fee         2
Duration    2
Discount    3
dtype: int64

In [52]:
tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [53]:
tech2 = tech.replace(np.nan, '')

tech2

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [54]:
tech3 = tech.replace({'Courses': np.nan, 'Fee': np.nan}, 'Pending')

tech3

   Courses      Fee Duration  Discount
0    Spark  20000.0      NaN    1000.0
1  Pending  25000.0   40days       NaN
2   Hadoop  Pending   35days    1500.0
3   Python  22000.0      NaN       NaN
4   pandas  24000.0   60days    2500.0
5  Pending  Pending   50days    2100.0
6     Java  22000.0   55days       NaN

In [55]:
tech.fillna('')
tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [56]:
emp_df = pd.read_csv('employee.csv')

emp_df

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [57]:
emp_df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [58]:
emp_df = emp_df.fillna(value={'Name': 'Verification Pending', 'Age': 'Unknown', 'Weight': 'Pending', 'Salary': 0.0})

emp_df

                    Name      Age   Weight     Salary
0                  James     36.0     75.0  5428000.0
1                Villers     38.0     74.0  3428000.0
2                  VKole     31.0     70.0  8428000.0
3                  Smith     34.0     80.0  4428000.0
4                  Gayle     40.0    100.0  4528000.0
5                   Adam     40.0  Pending  4528000.0
6                 Rooter     33.0     72.0  7028000.0
7               Peterson     42.0     85.0  2528000.0
8                  lynda     42.0     85.0        0.0
9   Verification Pending     42.0     85.0        0.0
10                 Jenny  Unknown    100.0    25632.0
11                  Kenn  Unknown    110.0    25632.0
12                   Aly  Unknown     90.0    25582.0
13                  John     41.0     85.0  1528000.0
14                   Ali     26.0     69.0        0.0

### Handling MIssing Values
 -   `df.isnull()` - to detect missing values (`.isna()` is the same thing)
 -   `df.fillna()` - to fill missing values (imputation)
  -   `df.dropna()` - to remove missing values
 -   `df.replace()`-  to replace specific values (imputation)

### Pandas Date & Time
-   `pd.to_datetime()` - convert different data types into datetime object
-   `pd.date_range()` - used to generate a range of date and time
-   `pd.timestamp()` - generate the time expressed as number of seconds since 01/01/1970

In [59]:
# generate a range of dates from start to end, default frequency
# period = number of dates you want between start and end (inclusive)

date_range = pd.date_range(start='07/01/2023', end='05/05/2026', periods=7)

print(date_range)

DatetimeIndex(['2023-07-01 00:00:00', '2023-12-21 04:00:00',
               '2024-06-11 08:00:00', '2024-12-01 12:00:00',
               '2025-05-23 16:00:00', '2025-11-12 20:00:00',
               '2026-05-05 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [60]:
date_range = pd.date_range(start='01/01/2020', end='05/05/2026',)

In [61]:
print(date_range
)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2026-04-26', '2026-04-27', '2026-04-28', '2026-04-29',
               '2026-04-30', '2026-05-01', '2026-05-02', '2026-05-03',
               '2026-05-04', '2026-05-05'],
              dtype='datetime64[us]', length=2317, freq='D')

In [62]:
start_date = '01/01/2023'
num_days=30

date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

np.random.seed(42)

stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

stock_df = pd.DataFrame({'Date': date_range, 'StockPrice':stock_prices})

stock_df

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [63]:
dates = ['2026-05-05', '2024-01-13', '2025-10-10']
print(dates)
print(type(dates))

output = pd.to_datetime

print(output)

['2026-05-05', '2024-01-13', '2025-10-10']
<class 'list'>
<function to_datetime at 0x146127b60>

In [64]:
input_list = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

print(input_list)

output = pd.to_datetime

['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

In [65]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [67]:
df['date_of_birth'].dtype

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [69]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')

df.head()

   patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00

In [70]:
df['date_of_birth'] = df['date_of_birth'].astype('str')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [71]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed', errors='coerce')

print('code still running after error')

df

code still running after error

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [ ]:
import 

tesla_df= pd.read_csv('tesla_stocks')
print(tesla_df)

FileNotFoundError: [Errno 2] No such file or directory: 'tesla_stocks'