In [1]:
import numpy as np
import pandas as pd

In [2]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

In [3]:
ser1 = pd.Series([10, 20, 30, 40], index=["A", "B", "C", "D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [4]:
d = {
    "b": 1,
    "a": 0,
    "c": 2,
    "d":100
}

ser2 = pd.Series(d)

In [5]:
d1 = {
    "a":0.0,
    "b":1.0,
    "c":2.0
}

ser3 = pd.Series(d1)

print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [6]:
calories = {'day1': 700,
            'day2': 2500,
            'day3': 1200}

ser4 = pd.Series(calories, index=['day1', 'day3'])

print(ser4)

day1     700
day3    1200
dtype: int64

In [7]:
ser5 = pd.Series(5.0, index=["a", "b", "c"])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

In [8]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

idx = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
purchases = pd.DataFrame(fruit_data, index= idx)

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [9]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [10]:
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [11]:
print(purchases.tail())

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

### EDA = Exploratory Data Analysis (The First Look)
- Data Profiling
    - Structure (shape)
    - Quality (missing values, duplicates, unique values)
    - Content (data types, dispersion, measure central tendency)

- Profiling Techniques
    - Data type and Format Validation
    - Statstical summaries (descriptive stats, values counts, frequency checks)
    - Uniqueness
    - Pattern Recognition
    - Cross Validation

In [12]:
cars_df = pd.read_json('data/cars.json')

cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [13]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [14]:
# gets a brief overview of descriptive stats(quantitative)
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [15]:
cars_df['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [16]:
cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [17]:
cars_df.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [18]:
cars_df.at[159, 'MPG']

np.float64(36.0)

In [19]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [20]:
e_df = pd.read_csv('data/employee.csv')

In [21]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [22]:
e_df3 =pd.read_csv('data/employee.csv')

e_df3

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

### Select Columns

In [23]:
df_cars = pd.read_json('data/cars.json')
df_cars.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [24]:
# accessing multiple values you use double brackets
df_cars.columns[[0, 1, 9]]

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [25]:
# accessing series with an index number
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [26]:
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

## Frequency Analysis - Value Counts

In [27]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

In [28]:
cat_df = pd.DataFrame(data)

In [29]:
cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [30]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

In [31]:
sales_df = pd.DataFrame(sales_data)

Frequency = sales_df['Brand'].value_counts()

print(Frequency)

frequent_product = Frequency[Frequency > 1].index[0]
print(Frequency)
print(f'This item appears more than once: {frequent_product}')

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
This item appears more than once: Samsung

In [32]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}

scores_df = pd.DataFrame(data)

In [33]:
score_counts = scores_df.value_counts(dropna=False) #dropna tells function to count nan values
print('Score', score_counts)

Score Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

### Sort Using Pandas

In [34]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}

In [35]:
grades_df = pd.DataFrame(data)

grades_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [36]:
print(grades_df.sort_values(by='Score 1'))

     Name  Height Qualification  Score 1  Score 2
3    Fadi     5.2           Msc       45       30
0    Jane     5.1           Msc       56       50
2   James     5.1           Msc       77       60
1  Princi     6.2            MA       86       96

In [37]:
cars = pd.read_json('data/cars.json')

### Slicing a dataframe with .iloc[] & .loc[]
-   `df.loc[ row:row , [colName , colName] ]` - label based indexing
-   `df.iloc[row:row, colNumber : colNumber]` - index based location

In [38]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]

In [39]:
e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [ ]:
e_df.iloc[:4]

Name        Gayle
Age            40
Weight        100
Salary    4528000
Name: 4, dtype: object

In [46]:
e_df.iloc[:,0:3]

       Name  Age  Weight
0     James   36      75
1   Villers   38      74
2     VKole   31      70
3     Smith   34      80
4     Gayle   40     100
5    Rooter   33      72
6  Peterson   42      85
7      John   41      85

In [49]:
e_df.iloc[:2, :2]

      Name  Age
0    James   36
1  Villers   38

In [50]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}

In [52]:
ball_up = pd.DataFrame(basketball)

ball_up.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [53]:
ball_up.loc[:, ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [58]:
ball_up.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G

### Handling MIssing Values
-   `df.isnull()` - to detect missing values (`.isna()` is the same thing)
-   `df.fillna()` - to fill missing values (imputation)
-   `df.dropna()` - to remove missing values
-   `df.replace()`-  to replace specific values (imputation)